config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root 'pages#index'
  resources :microposts do
    resources :comments, only: %i[create destroy]
    resource :likes, only: %i[create destroy]
  end
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  validates :comment_content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :micropost
  belongs_to :user
  validates :micropost_id, uniqueness: { scope: :user_id }
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  paginates_per 12
  validates :name, :youtube_url, :content, presence: true
  before_save :slugify
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  def slugify
    self.youtube_url = youtube_url.last(11)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_microposts, through: :likes, source: :micropost
  has_many :comments, dependent: :destroy

  validates :username, presence: true
  validates :password, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable

  def self.guest
    find_or_create_by!(username: 'ゲストユーザー', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.confirmed_at = Time.now
    end
  end

  def already_liked?(micropost)
    likes.exists?(micropost_id: micropost.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    root_path
  end

  private

  def sign_in_required
    redirect_to new_user_session_url unless user_signed_in?
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      flash[:notice] = 'コメントに成功しました!!'
      redirect_to micropost_path(@comment.micropost)
    else
      flash[:alert] = 'コメントに失敗しました'
      @micropost = @comment.micropost
      @comments = @micropost.comments.includes(:user)
      render 'microposts/show'
    end
  end

  def destroy
    comment = Comment.find_by(id: params[:id], micropost_id: params[:micropost_id])
    comment.destroy
    flash[:notice] = 'コメントを削除しました'
    redirect_to micropost_path(comment.micropost)
  end

  private

  def comment_params
    params.require(:comment).permit(:comment_content).merge(user_id: current_user.id, micropost_id: params[:micropost_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @micropost = Micropost.find(params[:micropost_id])
    @like = current_user.likes.create(micropost_id: params[:micropost_id])
  end

  def destroy
    @micropost = Micropost.find(params[:micropost_id])
    @like = current_user.likes.find_by(micropost_id: @micropost.id)
    @like.destroy
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: %i[show edit update]
  before_action :authenticate_user!, only: %i[new edit destroy create show index]

  def new
    @micropost = Micropost.new
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    @micropost.user_id = current_user.id
    url = params[:micropost][:youtube_url]
    url = url.last(11)
    @micropost.youtube_url = url

    if @micropost.save
      flash[:notice] = '投稿に成功しました!!'
      redirect_to microposts_path(@micropost)
    else
      flash[:error] = '投稿に失敗しました' 
      render :new
    end
  end

  def show
    @micropost = Micropost.find(params[:id])
    @comment = Comment.new
    @comments = @micropost.comments.includes(:user)
  end

  def edit
    if @micropost.user != current_user
      flash[:alert] = '不正なアクセスです'
      redirect_to microposts_path
    end
  end

  def index
    @microposts = Micropost.page(params[:page]).per(12).order('updated_at DESC')
  end

  def update
    if @micropost.update(micropost_params)
      flash[:notice] = '更新しました'
      redirect_to micropost_path(@micropost)
    else
      render :edit
    end
  end

  def destroy
    micropost = Micropost.find(params[:id])
    micropost.destroy
    flash[:notice] = '削除しました'
    redirect_to microposts_path(@micropost)
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :youtube_url, :name)
  end

  def set_micropost
    @micropost = Micropost.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :sign_in_required, only: [:show]

  def index; end

  def show; end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to new_user_session_path, alert: 'ゲストユーザーのパスワード再設定はできません。'
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: %i[update destroy]

  def ensure_normal_user
    redirect_to edit_user_registration_path, alert: 'ゲストユーザーの更新・削除はできません。' if resource.email == 'guest@example.com'
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit; end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_alert(key)
    case key
    when 'alert'
      'warning'
    when 'notice'
      'success'
    when 'error'
      'danger'
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/_like.html.erb
<% if current_user.already_liked?(@micropost) %>
  <%= link_to micropost_likes_path(@micropost), method: :delete, remote: true do %>
  <i class="fas fa-heart fa-lg" style="color: red;"></i>
  <% end %>
 <%= @micropost.likes.count %>
<% else %>
  <%= link_to micropost_likes_path(@micropost), method: :post, remote: true do %>
  <i class="far fa-heart fa-lg"></i>
  <% end %>
  <%= @micropost.likes.count %>
<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @micropost.id %>').html("<%= j(render 'likes/like', micropost: @micropost) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @micropost.id %>').html("<%= j(render partial: 'likes/like', locals: {micropost: @micropost}) %>");

app/views/microposts/_form.html.erb
 <%= form_with model: micropost do |f| %>
 <div class="container">
 <div class="row">
  <div class="form-group col-xs-8 col-md-8 col-lg-8 mx-auto">
  
  <%= render 'layouts/error_messages', model: f.object %>
  <%= f.label :name, "タイトル", class: "label" %>
  <%= f.text_field :name, class: 'form-control', autocomplete: "off" %>
</div>
<div class="form-group col-xs-8 col-md-8 col-lg-8 mx-auto ">
 <%= f.label :youtube_url, "YOUTUBE URL", class: "label" %>
 <%= f.text_field :youtube_url, class: 'form-control', autocomplete: "off" %>
 <p>※ URLはYOUTUBE動画下部にある共有からコピーしてください</p>
</div>
<div class="form-group col-xs-8 col-md-8 col-lg-8 mx-auto ">
 <%= f.label :content, "評価", class: "label" %>
 <%= f.text_area :content, class: 'form-control', autocomplete: "off" %>
</div>

<%= f.submit '投稿', class: "col-xs-3 col-md-7 col-lg-8 btn btn-dark mx-auto"%>
  <% end %>
 </div>
 </div>
 </div>

app/views/microposts/edit.html.erb
<div class="continer">
  <div class="row">
  <h1 class="mx-auto">新しい投稿</h1>
  </div>
</div>
<%= render 'form', micropost: @micropost %>

app/views/microposts/index.html.erb
 <div class="container-fluid">
  <div class="row">
   <% @microposts.each do |micropost| %>
     <div class="card col-xs-8 col-md-4 col-lg-3 " style="width: 280px;">
	   <img class="card-img-top" src="http://img.youtube.com/vi/<%= micropost.youtube_url.last(11)%>/hqdefault.jpg" alt="カード画像">
	    <div class="card-body">
		  <h6 class="card-title"><%= micropost.name %></h6>
      いいね数:<%= micropost.likes.count %><br>
      コメント数:<%= micropost.comments.count%><br>
      <%= link_to "詳細", micropost_path(micropost),method: :get, class: "btn btn-primary" %><br>
      投稿者:<%= micropost.user.username %>
	   </div>
    </div>
   <% end %>
	 </div>
 </div>
</div>


 <%= paginate @microposts %>

app/views/microposts/new.html.erb
<div class="continer">
 <div class="row">
 <h1 class="mx-auto">新しい投稿</h1>
 </div>
</div>
<%= render 'form', micropost: @micropost %>

app/views/microposts/show.html.erb
<div class="container">
 <div class="row">
  <div class=" card col-xs-12 col-sm-11 col-md-18 col-lg-8 mx-auto ">
   <div class="embed-responsive embed-responsive-16by9">
    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/<%= @micropost.youtube_url.last(11)%>"  allowfullscreen></iframe>
   </div>
     <div class="card-body">
      <h2><%= @micropost.name %></h2>
      <p class="card-text"><%= @micropost.content %></p>
      <% if @micropost.user.id == current_user.id %>
      <%= link_to "編集画面へ", edit_micropost_path(@micropost), class: "btn btn-primary" %>
      <%= link_to "削除する", micropost_path(@micropost), method: :delete, class: "btn btn-primary" %>
      <% end %>
      <div id="likes_buttons_<%= @micropost.id %>">
      <%= render 'likes/like', micropost: @micropost %>
      <p><%= @micropost.created_at%></p>
      </div>
    </div>         
   </div>
  </div>
  
<h4 class="text-center">＜コメント一覧＞</h4>

<table class="table col-lg-8 mx-auto ">
  <thead>
    <tr>
      <th scope="col">ユーザー名</th>
      <th scope="col">内容</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <% @comments.each do |comment| %>
  <tbody>
    <tr>
      <td><strong><%= comment.user.username %>：</strong></td>
      <td><%= comment.comment_content %></td>
      <% if user_signed_in? && current_user.id == comment.user_id %>
      <td><%= link_to "削除", micropost_comment_path(comment.micropost.id, comment.id), method: :delete %>
    </td>
    <% end %>
    <% end %>
    </tr>
    </tbody>
</table>
<div class="form-group col-lg-8 mx-auto ">
<% if user_signed_in? %>
  <%= form_with model: [@micropost, @comment], local: true do |form| %>
    <%= form.text_area :comment_content, placeholder: "コメントする", rows: "3", class: 'form-control' %>
    <%= form.submit "送信" %>
  <% end %>
<% else %>
  <strong><p>コメントの投稿には新規登録/ログインが必要です</p></strong>
<% end %>
</div>

</div>
</div>