config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root 'pages#index'
  resources :microposts do
    resources :comments, only: %i[create destroy]
    resource :likes, only: %i[create destroy]
  end
  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  validates :comment_content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :micropost
  belongs_to :user
  validates :micropost_id, uniqueness: { scope: :user_id }
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  paginates_per 12
  validates :name, :youtube_url, :content, presence: true
  before_save :slugify
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  def slugify
    self.youtube_url = youtube_url.last(11)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_microposts, through: :likes, source: :micropost
  has_many :comments, dependent: :destroy

  validates :username, presence: true
  validates :password, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable

  def self.guest
    find_or_create_by!(username: 'ゲストユーザー', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.confirmed_at = Time.now
    end
  end

  def already_liked?(micropost)
    likes.exists?(micropost_id: micropost.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    root_path
  end

  private

  def sign_in_required
    redirect_to new_user_session_url unless user_signed_in?
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      flash[:notice] = 'コメントに成功しました!!'
      redirect_to micropost_path(@comment.micropost)
    else
      flash[:alert] = 'コメントに失敗しました'
      @micropost = @comment.micropost
      @comments = @micropost.comments.includes(:user)
      render 'microposts/show'
    end
  end

  def destroy
    comment = Comment.find_by(id: params[:id], micropost_id: params[:micropost_id])
    comment.destroy
    flash[:notice] = 'コメントを削除しました'
    redirect_to micropost_path(comment.micropost)
  end

  private

  def comment_params
    params.require(:comment).permit(:comment_content).merge(user_id: current_user.id, micropost_id: params[:micropost_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @micropost = Micropost.find(params[:micropost_id])
    @like = current_user.likes.create(micropost_id: params[:micropost_id])
  end

  def destroy
    @micropost = Micropost.find(params[:micropost_id])
    @like = current_user.likes.find_by(micropost_id: @micropost.id)
    @like.destroy
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: %i[show edit update]
  before_action :authenticate_user!, only: %i[new edit destroy create show index]

  def new
    @micropost = Micropost.new
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    @micropost.user_id = current_user.id
    url = params[:micropost][:youtube_url]
    url = url.last(11)
    @micropost.youtube_url = url

    if @micropost.save
      flash[:notice] = '投稿に成功しました!!'
      redirect_to microposts_path(@micropost)
    else
      flash[:error] = '投稿に失敗しました' 
      render :new
    end
  end

  def show
    @micropost = Micropost.find(params[:id])
    @comment = Comment.new
    @comments = @micropost.comments.includes(:user)
  end

  def edit
    if @micropost.user != current_user
      flash[:alert] = '不正なアクセスです'
      redirect_to microposts_path
    end
  end

  def index
    @microposts = Micropost.page(params[:page]).per(12).order('updated_at DESC')
  end

  def update
    if @micropost.update(micropost_params)
      flash[:notice] = '更新しました'
      redirect_to micropost_path(@micropost)
    else
      render :edit
    end
  end

  def destroy
    micropost = Micropost.find(params[:id])
    micropost.destroy
    flash[:notice] = '削除しました'
    redirect_to microposts_path(@micropost)
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :youtube_url, :name)
  end

  def set_micropost
    @micropost = Micropost.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :sign_in_required, only: [:show]

  def index; end

  def show; end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to new_user_session_path, alert: 'ゲストユーザーのパスワード再設定はできません。'
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit; end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_alert(key)
    case key
    when 'alert'
      'warning'
    when 'notice'
      'success'
    when 'error'
      'danger'
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= bootstrap_alert(key)%> close-flash">
    <%= value %>
    <button type="button" class="close close-button" data-dismiss="alert">
    <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
 <nav class="navbar navbar-expand navbar-dark bg-dark ">
      <%= link_to "VideoApp", root_path, id: "logo", class: "navbar-brand" %>
      <ul class="navbar-nav ml-auto">
       <% if user_signed_in? %>
       <li class="nav-item">
          <%= link_to "投稿", new_micropost_path, class: "nav-link" %>
        </li>
       <li class="nav-item">
          <%= link_to "投稿一覧", microposts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "プロフィール", edit_user_registration_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
 </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
  </head>

  <body>
  <header>
  <%= render 'layouts/navbar' %>
  </header>
    <%= render 'layouts/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
  <div class="jumbotron jumbotron-fluid jumbotron-extend">
    <div class="container">
      <div class="row">
       <div class="content col-12">
        <h2 class="display-4 text-center text-white">VideoAppへようこそ!!</h2><br>
         <p class="lead text-center text-white">アニメ、映画、ドラマを共有しましょう!!</p><br>
         <div class="content-button text-center">
         <% if user_signed_in? %>
         <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-dark m-4 col-6 text-center" %>
         <% else %>
         <%= link_to "新規登録", new_user_registration_path, class: "btn btn-dark m-4 col-6 text-center"%>
         <br>
         <%= link_to "ログイン", new_user_session_path, class: "btn btn-dark m-4 col-3 mx-auto"%>
         <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class: "btn btn-dark m-4 col-3 mx-auto" %>
         <% end %>
         </div>
       </div>
      </div>
    </div>
   </div>